#!/bin/bash

# 单GPU训练 (修复NCCL重复GPU错误)
CUDA_VISIBLE_DEVICES=0 python pretraining.py \
    --model_name_or_path ../model/Qwen/Qwen3-0.6B \
    --train_file_dir ../data/pretrain \
    --validation_file_dir ../data/pretrain \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --do_train \
    --do_eval \
    --use_peft True \
    --seed 42 \
    --max_train_samples 1000 \
    --max_eval_samples 10 \
    --num_train_epochs 0.1 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 5 \
    --eval_steps 20 \
    --eval_strategy steps \
    --save_steps 100 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 16 \
    --preprocessing_num_workers 4 \
    --block_size 256 \
    --group_by_length True \
    --output_dir ../output/pretrain_single_gpu_mp \
    --overwrite_output_dir \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --dtype bfloat16 \
    --bf16 \
    --device_map auto \
    --report_to tensorboard \
    --gradient_checkpointing True \
    --cache_dir ../output/cache